apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
  labels:
    app: hw
spec:
  replicas: 1
  template:
    metadata:
      name: hw
      labels:
        app: hw
    spec:
      containers:
        - name: hw
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          args:
            - /bin/sh
            - -c
            - "echo $(param1);echo $(param2);echo $(param3);echo $(param4); sleep infinity"
      restartPolicy: Always
  selector:
    matchLabels:
      app: hw
